name: Build and Deploy Portfolio

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Compile fetchPinnedRepos script
        run: npx tsc scripts/fetchPinnedRepos.ts --outDir scripts-build --module commonjs && mv scripts-build/fetchPinnedRepos.js scripts-build/fetchPinnedRepos.cjs

      - name: Fetch GitHub pinned repos
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAGES_DEPLOY_TOKEN }}
        run: node scripts-build/fetchPinnedRepos.cjs

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAGES_DEPLOY_TOKEN }}
          publish_dir: ./dist
